name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Run setup script
        run: echo "Test Author\ntest.author@example.com\ntestauthor\n\n\n\n" | sh ./setup.sh

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with: 
          composer-options: "--no-interaction --no-suggest --ignore-platform-reqs"

      - name: Run PHP tests
        run: vendor/bin/phpunit